version: "3.3"

services:
  db:
    container_name: "mysql"
    image: mysql:5.7
    ports:
      - 3307:3306
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: transfer
      MYSQL_USER: rootuser
      MYSQL_PASSWORD: rootroot
    networks:
      - bank
  app:
    container_name: "bank-transfer"
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8000:80
    volumes:
      - ./:/app
      - $GOPATH/pkg/mod/cache:/go/pkg/mod/cache
    networks:
      - bank
    depends_on:
      - db
    links:
      - db
    networks:
      - bank
    #   - postgres

  
volumes:
  db_data: {}
networks:
  bank:
    driver: bridge